export const data = {
    "Name_Last_First_MI": "David Jones",
    "Social_Security_Number": "123456",
    "Address_Apartment": "abc street, 123 city",
    "Date_of_Birth": "19052000",
    "City_State_and_Zip_Code": "abcx yzs 400003",
    "Phone_Number": "9876543210",
    "Name_of_authorized_representative_Last_First_MI": "David Jones",
    "Phone_Number1": "",
    "Address_of_authorized_representative_Apartment": "",
    "City_State_and_Zip_Code_of_authorized_representati": "",
    "Ohio_Department_of_Job_and_Family_Services": "",
    "Ohio_Home_Care_Waiver": "",
    "Other1": "",
    "Text3a": "",
    "Mental_Reta_rdationDevel_op_mental_Disabilities_sp": "",
    "Individual_Options_Waiver": "",
    "Residential_Facility_Waiver": "",
    "Level_I_Waiver": "",
    "Other2": "",
    "Text3": "",
    "Ohio_Department_of_Aging_specify_waiver": "",
    "PASSPORT_Waiver": "",
    "CHOICES_Waiver": "",
    "Other3": "",
    "Text3b": "",
    "Other_specify": "",
    "Text3c": "",
    "Date1": "",
    "Date2": "",
    "Text4": "",
    "Name_of_CDJFS_Case_Worker_please_print": "",
    "Yes": "",
    "Text1": "",
    "Text2": "",
    "Date_Received_By_CDJFS": ""
}
